package com.zpark.neimin.first.model;

public class Sys {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys.id
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys.code
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys.name
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys.id
     *
     * @return the value of sys.id
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys.id
     *
     * @param id the value for sys.id
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys.code
     *
     * @return the value of sys.code
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys.code
     *
     * @param code the value for sys.code
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys.name
     *
     * @return the value of sys.name
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys.name
     *
     * @param name the value for sys.name
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}