package com.zpark.neimin.first.dao;

import com.zpark.neimin.first.model.Sys;
import com.zpark.neimin.first.model.SysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    long countByExample(SysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    int deleteByExample(SysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    int insert(Sys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    int insertSelective(Sys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    List<Sys> selectByExample(SysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    Sys selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Sys record, @Param("example") SysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    int updateByExample(@Param("record") Sys record, @Param("example") SysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    int updateByPrimaryKeySelective(Sys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys
     *
     * @mbg.generated Fri Sep 20 09:28:34 CST 2019
     */
    int updateByPrimaryKey(Sys record);
}